### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by mfrasca** [dimitarvp/xqlite#1]
is [this](https://github.com/elixir-sqlite/sqlite_ecto2/issues/238#issuecomment-507869487) the roadmap?

> *    I found a lot of configuration options for Sqlite3 which I want to expose to an underlying raw Sqlite3 library, not the Ecto adapter itself.
> *    I want to avoid Mix.Config since it's now deprecated (in Elixir 1.9). I'm gonna experiment in my repo with a process dictionary configuration, or GenServer state. Not yet determined.
> *    I am not interested in supporting very old Elixir versions, not to mention that one of the Sqlitex dependencies mandates Elixir 1.7 anyway.

sounds like you want to put it in the README for the project, not so?

**Comment by dimitarvp** [comment]
Just added a roadmap and some notes: https://github.com/dimitarvp/xqlite/commit/3a12bff0693364b5ad9db8def8a79d6caf69d79c
